// <auto-generated />
using ExamSoftwareDev.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamSoftwareDev.Migrations
{
    [DbContext(typeof(IngredientContext))]
    [Migration("20241219114320_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ExamSoftwareDev.Logic.Ingredient.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000.0,
                            Category = "Produce",
                            Name = "New potatoes",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 8.0,
                            Category = "Liquids",
                            Name = "Oil",
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 8.0,
                            Category = "Produce",
                            Name = "Leeks",
                            Unit = "large"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 400.0,
                            Category = "Meat",
                            Name = "Peppered smoked mackerel",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 16.0,
                            Category = "Dairy",
                            Name = "Eggs",
                            Unit = "normal"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 8.0,
                            Category = "Other",
                            Name = "Creamed horseradish",
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1200.0,
                            Category = "Other",
                            Name = "Gnocchi",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 8.0,
                            Category = "Dairy",
                            Name = "Unsalted butter",
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 240.0,
                            Category = "Dairy",
                            Name = "Parmesan",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 8.0,
                            Category = "Spices",
                            Name = "Black pepper",
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 4.0,
                            Category = "Liquids",
                            Name = "Rapeseed oil",
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 8.0,
                            Category = "Produce",
                            Name = "Red onions",
                            Unit = "units"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 1200.0,
                            Category = "Produce",
                            Name = "Kale",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 1200.0,
                            Category = "Other",
                            Name = "Wholemeal pasta",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 16.0,
                            Category = "Dairy",
                            Name = "Soft cheese",
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 16.0,
                            Category = "Other",
                            Name = "Pesto",
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 4800.0,
                            Category = "Produce",
                            Name = "Spinach",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 60.0,
                            Category = "Dairy",
                            Name = "Butter",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 24.0,
                            Category = "Meat",
                            Name = "Salmon",
                            Unit = "fillets"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 1200.0,
                            Category = "Dairy",
                            Name = "Double cream",
                            Unit = "ml"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
